name: my_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy=2.1.3
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - pillow=11.0.0
  - pyzmq=26.2.0
  - tornado=6.4.2
  - psutil=6.1.0
  - traitlets=5.14.3
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - nest-asyncio=1.6.0
  - typing_extensions=4.12.2
  - pytz=2024.2
  - python-dateutil=2.9.0.post0

  - pip:
      - asttokens==2.4.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.9
      - decorator==5.1.1
      - executing==2.1.0
      - fonttools==4.55.0
      - kiwisolver==1.4.7
      - packaging==24.2
      - parso==0.8.4
      - platformdirs==4.3.6
      - prompt_toolkit==3.0.48
      - pure_eval==0.2.3
      - Pygments==2.18.0
      - pyparsing==3.2.0
      - stack-data==0.6.3
      - wcwidth==0.2.13
      - six==1.16.0
